### ISSUE TITLE
permission to integrate your code in another repo

### ISSUE THREAD

**Issue by NecrCode** [tdsat/YaogUI#1]
Hey, I've used your mod and i liked it, i was intending to add some more features to your mod, but found that your repo hasn't been active for a while, i wasn't sure whether i should proceed or not, but when i came across [iguanacore's repo ](https://github.com/iguanacore/iguana_acs_functions)(which was(still) active) and i went with his repo.
but as i said, i liked your mod and i want to continue to use it, so i'd like to ask for your permission to integrate it into iguana's overhaul mod.

**Comment by tdsat** [comment]
@NecrCode Sorry for the delayed reply, haven't been here in a while. Yeap, feel free to integrate it with any other mod you wish. Credit is appreciated but not required. 

As far as features are concerned, I'd appreciate an PRs :)

Have fun!

**Comment by NecrCode** [comment]
> Sorry for the delayed reply, haven't been here in a while. Yeap, feel free to integrate it with any other mod you wish. Credit is appreciated but not required

thank you @tdsat, and you deserve every bit of credit my friend.

> As far as features are concerned, I'd appreciate an PRs :)

i'll definitely do so.

---
edit: it's weird how github didn't notify me of your reply, zero notification!?
